# Generated by Django 5.1.5 on 2025-01-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='username',
        ),
    ]
