# Generated by Django 5.1.5 on 2025-01-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_rename_full_name_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='full_name',
        ),
    ]
