# Generated by Django 5.1.5 on 2025-03-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_address_address_remove_address_zip_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
