# Generated by Django 5.1.5 on 2025-04-04 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_review_unique_together'),
        ('customer', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
